### ISSUE TITLE
It seems that your package doesn't work

### ISSUE THREAD

**Issue by xiongzhp** [fragro/meteor-pubreader#1]
It seems this meteor package is full of bugs, have you ever tested it? The template has bugs like "pubreader.html:173: Unexpected character in attribute value".

**Comment by xiongzhp** [comment]
Uncaught TypeError: Cannot set property 'rendered' of undefined

**Comment by fragro** [comment]
Hey @xiongzhp this project was deprecated by the company I was developing it for, but it fell by the wayside. What are you using it for? It is based on a very old version of meteor, I am sure it needs updating by now.

**Comment by xiongzhp** [comment]
Hope you can take a look at this project: https://github.com/xiongzhp/acadxreader.git
